### ISSUE TITLE
Focus jumps back to last saved input

### ISSUE THREAD

**Issue by robertdean** [DmitryEfimenko/ng-auto-save#1]
Scenario:
1. Type something on the first element in the plunkr demo.
2. Tab to the next element and start typing before the first finishes saving.
3. When the first element finishes saving, the focus is taken away from the second element and moved back to the first element.

This is unexpected behavior.

Note: This is a very cool idea. Good job!

**Comment by DmitryEfimenko** [comment]
tl;dr: it's fixed

This was caused by the fact that input when disabled for when the saving is in progress was losing its focus. So there was a code to re-focus it after saving is complete.
I replaced disabling input with a simple queuing mechanism, which is a better UX anyway.

**Comment by robertdean** [comment]
I like it. +1 for elegant solution.
