### ISSUE TITLE
auto-saving & auto-saved

### ISSUE THREAD

**Issue by pliolis** [DmitryEfimenko/ng-auto-save#3]
I can’t make these two directive to work properly (auto-saving & auto-saved).
In your demo in Plnkr I see the same (the gear and the square icons are not appeared during the saving process. They always have ng-hide class set. This class is never removed during the saving process.).
Debugging your code I found that in the function that changes the visibility of these elements (line 27):

```
function changeVisibility(elArr, col, shouldShow) {
                    for (var j = 0, jl = elArr.length; j < jl; j++) {
                        if (elArr[j].col == col && elArr[j].key == self.key) {
                            if (shouldShow)
                                elArr[j].el.removeClass('ng-hide');
                            else
                                elArr[j].el.addClass('ng-hide');
                            break;
                        }
                    }
                }
```

The elArr[j].key value is always ‘undefined’. So the condition is always false and the class 'ng-hide' is never removed.
This array is initialized with ‘undefined’ value on key property and not with the actual value of key field of the model.

**Comment by pliolis** [comment]
In the previous version (Feb 27, 2015) it works!

**Comment by DmitryEfimenko** [comment]
fixed in the latest and updated plunker.
Please let me know if it still does not work for you.

**Comment by pliolis** [comment]
In plunker does not work too

**Comment by DmitryEfimenko** [comment]
You sure? I updated it couple minutes ago and it seems to work for me. Did you re-open it?

**Comment by pliolis** [comment]
Yes it is ok now. 
Thank you.
