### ISSUE TITLE
$scope[autoSaveFnName] is not a function when using controller as

### ISSUE THREAD

**Issue by chiptus** [DmitryEfimenko/ng-auto-save#7]
Thank you very much for this package, makes my life easier every day :)
I'm trying to refactor my code from scope soup to using controller aliasing (controllerAs). But it seems like ng-auto-save needs my function to be on the scope. 

Do you think there's a way to handle it? instead of save the function on $scope?

Thanks

**Comment by DmitryEfimenko** [comment]
I didn't check, but I think you could just write out your controller in the `auto-save` directive.
So instead `auto-save="updateField"` you'd write `auto-save="ctrl.updateField"`
Let me know if that does not work for you, and I'd appreciate a plunker showing the issue.
You can fork [this one](http://plnkr.co/edit/7HIAXH?p=preview) if you'd like:

**Comment by chiptus** [comment]
Ok, took me some time but I made a  [plunker](https://plnkr.co/edit/v8ff6EwICxMlC09l8vyq?p=preview)

When I'm changing the item, you see the saving tag, but then you get the following error: 

```
VM1481 ng-auto-save.js:169 TypeError: $scope[autoSaveFnName] is not a function
    at save (VM1481 ng-auto-save.js:151)
    at runQueue (VM1481 ng-auto-save.js:133)
    at VM1481 ng-auto-save.js:120
    at VM1479 angular.min.js:160
    at f (VM1479 angular.min.js:45)
    at VM1479 angular.min.js:48
```

**Comment by DmitryEfimenko** [comment]
well, for one, in that plunker you aren't using `controllerAs` syntax. Did you not save it before posting the link or something?

**Comment by chiptus** [comment]
I'm using a component. It's controller is automatically bound to $ctrl

**Comment by DmitryEfimenko** [comment]
that issue does not exist in the latest version. Make sure you use latest.

**Comment by chiptus** [comment]
The plunker is using the same file that is in this repository, so I guess I am using the latest

**Comment by DmitryEfimenko** [comment]
the file to use is in the dist folder. I updated the plunker link too.

**Comment by chiptus** [comment]
works now, thx.
